### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa-vue#3]
Hi,
I ran the install steps and everything works fine until I run npm start.

Here is my output:

``` shell
> sympa-vue@0.0.1 start /home/verdin/sympa-vue
> NODE_ENV=development webpack-dev-server --progress --colors

/home/verdin/sympa-vue/webpack.config.js:2
const { addPlugins, createConfig, defineConstants, resolveAliases, env, entryPoint, setOutput, sourceMaps } = require('@webpack-blocks/webpack2');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/verdin/sympa-vue/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/verdin/sympa-vue/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! sympa-vue@0.0.1 start: `NODE_ENV=development webpack-dev-server --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sympa-vue@0.0.1 start script 'NODE_ENV=development webpack-dev-server --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sympa-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development webpack-dev-server --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sympa-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sympa-vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/verdin/sympa-vue/npm-debug.log
```

**Comment by ludovicm67** [comment]
Hi!

The issue is that your Node version seems to be to old to run the app.
You will need to upgrade at least to the version 6 so that it can understand ES6.

I'll fix the documentation in a few minutes.
